import { NextRequest, NextResponse } from 'next/server';
import connectDB from '@/lib/mongodb';
import { Exam } from '@/lib/models/Exam';

export const dynamic = 'force-dynamic';

// POST — receives pre-generated questions from the client and saves the exam
export async function POST(request: NextRequest) {
  try {
    await connectDB();
    const body = await request.json();
    const {
      teacherId,
      title,
      subject,
      description,
      examDate,
      startTime,
      durationMins,
      targetPrograms,
      targetYears,
      targetBatches,
      shuffleQuestions,
      shuffleOptions,
      showResultImmediately,
      questions, // pre-generated by the AI flow on the client
    } = body;

    if (!teacherId || !title || !durationMins || !Array.isArray(questions) || questions.length === 0) {
      return NextResponse.json(
        { error: 'teacherId, title, durationMins, and questions are required' },
        { status: 400 }
      );
    }

    const totalMarks = questions.length;

    const exam = await Exam.create({
      teacherId,
      title,
      subject:     subject     || '',
      description: description || '',
      examDate:    examDate    || '',
      startTime:   startTime   || '',
      durationMins: Number(durationMins),
      totalQuestions:        questions.length,
      totalMarks,
      passingMarks:          Math.ceil(totalMarks * 0.4),
      shuffleQuestions:      !!shuffleQuestions,
      shuffleOptions:        !!shuffleOptions,
      showResultImmediately: showResultImmediately !== false,
      targetPrograms:  targetPrograms  || [],
      targetYears:     targetYears     || [],
      targetBatches:   targetBatches   || [],
      questions,
      status: 'published',
    });

    return NextResponse.json(exam, { status: 201 });
  } catch (error: any) {
    console.error('Save scheduled exam error:', error);
    return NextResponse.json({ error: error.message || 'Failed to save exam' }, { status: 500 });
  }
}

// GET — list all exams for a teacher
export async function GET(request: NextRequest) {
  try {
    await connectDB();
    const { searchParams } = new URL(request.url);
    const teacherId = searchParams.get('teacherId');

    const all = searchParams.get('all');
    if (!teacherId && !all) {
      return NextResponse.json({ error: 'teacherId or all=1 is required' }, { status: 400 });
    }

    const filter = teacherId ? { teacherId } : {};
    const exams = await Exam.find(filter).sort({ createdAt: -1 }).lean();
    return NextResponse.json(exams);
  } catch (error: any) {
    console.error('GET scheduled exams error:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
