'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useToast } from '@/hooks/use-toast';
import { getCurrentUser } from '@/lib/mock-db';
import {
  Loader2, Sparkles, Calendar, Clock, Users,
  CheckCircle2, ClipboardList, Brain, BookOpen,
  MessageSquare, Calculator, BarChart2, Trash2, Pencil,
} from 'lucide-react';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from '@/components/ui/dialog';

interface ReviewQuestion {
  questionText: string;
  questionType: string;
  options: { label: string; text: string; isCorrect: boolean }[];
  explanation: string;
  marks: number;
  difficulty: string;
  topic: string;
  section: string;
}

interface ScheduledExam {
  _id: string;
  title: string;
  subject: string;
  examDate: string;
  startTime: string;
  durationMins: number;
  totalQuestions: number;
  status: string;
  createdAt: string;
}

const PROGRAMS   = ['BCA', 'BCA(DS)', 'BCom', 'MSc(ADS)', 'MCom', 'MCA', 'MCA GenAI'];
const YEARS      = [1, 2, 3, 4];
const DIFFICULTIES = [
  { value: 'easy',   label: 'Easy' },
  { value: 'medium', label: 'Medium' },
  { value: 'hard',   label: 'Hard' },
];
const COMPANY_TYPES = [
  { value: 'any',     label: 'Any Company',                       desc: 'Balanced for all placement drives' },
  { value: 'service', label: 'Service-based (TCS, Infosys, Wipro)', desc: 'Aptitude-heavy, fundamentals' },
  { value: 'product', label: 'Product-based (Amazon, Google)',      desc: 'DSA, algorithms, problem solving' },
  { value: 'core',    label: 'Core / Domain',                      desc: 'Applied engineering concepts' },
];

const SECTION_META = [
  { key: 'technical', label: 'Technical',        icon: BookOpen,      color: 'text-blue-600',   bg: 'bg-blue-50',   border: 'border-blue-200',   ring: 'ring-blue-400'   },
  { key: 'aptitude',  label: 'Quantitative Aptitude', icon: Calculator, color: 'text-amber-600', bg: 'bg-amber-50',  border: 'border-amber-200',  ring: 'ring-amber-400'  },
  { key: 'reasoning', label: 'Logical Reasoning', icon: Brain,         color: 'text-purple-600', bg: 'bg-purple-50', border: 'border-purple-200', ring: 'ring-purple-400' },
  { key: 'verbal',    label: 'Verbal Ability',    icon: MessageSquare, color: 'text-green-600',  bg: 'bg-green-50',  border: 'border-green-200',  ring: 'ring-green-400'  },
] as const;

function formatDate(iso: string) {
  if (!iso) return '—';
  return new Date(iso).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
}

function statusColor(status: string) {
  if (status === 'published')  return 'bg-green-100 text-green-700';
  if (status === 'completed')  return 'bg-blue-100 text-blue-700';
  if (status === 'draft')      return 'bg-yellow-100 text-yellow-700';
  return 'bg-slate-100 text-slate-600';
}

export default function ScheduleExamPage() {
  const { toast } = useToast();
  const router = useRouter();

  const [exams, setExams]         = useState<ScheduledExam[]>([]);
  const [loadingData, setLoadingData] = useState(true);

  // Core fields
  const [subject, setSubject]         = useState('');
  const [difficulty, setDifficulty]   = useState('medium');
  const [companyType, setCompanyType] = useState('any');
  const [customTitle, setCustomTitle] = useState('');

  // Section distribution
  const [sections, setSections] = useState({ technical: 15, aptitude: 10, reasoning: 10, verbal: 5 });

  // Schedule fields
  const [examDate, setExamDate]         = useState('');
  const [startTime, setStartTime]       = useState('');
  const [durationMins, setDurationMins] = useState(60);

  // Target audience
  const [selectedPrograms, setSelectedPrograms] = useState<string[]>([]);
  const [selectedYears, setSelectedYears]       = useState<number[]>([]);

  // Options
  const [shuffleQ, setShuffleQ]       = useState(true);
  const [shuffleOpts, setShuffleOpts] = useState(true);

  const [generating, setGenerating]   = useState(false);
  const [successDialog, setSuccessDialog] = useState(false);
  const [lastCreated, setLastCreated]     = useState<ScheduledExam | null>(null);

  // Review step — questions generated by AI, editable before publishing
  const [reviewQuestions, setReviewQuestions] = useState<ReviewQuestion[] | null>(null);
  const [reviewTitle, setReviewTitle]         = useState('');
  const [publishing, setPublishing]           = useState(false);

  // Reschedule modal for existing exams
  const [rescheduleTarget, setRescheduleTarget] = useState<ScheduledExam | null>(null);
  const [rsDate, setRsDate]                     = useState('');
  const [rsTime, setRsTime]                     = useState('');
  const [rescheduling, setRescheduling]         = useState(false);

  const totalQuestions = sections.technical + sections.aptitude + sections.reasoning + sections.verbal;

  const loadData = async () => {
    setLoadingData(true);
    try {
      const user = getCurrentUser();
      if (!user) return;
      const userId = (user as any)._id || (user as any).id;
      const eRes = await fetch(`/api/exams/ai-schedule?teacherId=${userId}`);
      const eData = await eRes.json();
      setExams(Array.isArray(eData) ? eData : []);
    } catch (e) {
      console.error(e);
    } finally {
      setLoadingData(false);
    }
  };

  const handleReschedule = async () => {
    if (!rescheduleTarget) return;
    setRescheduling(true);
    try {
      const res = await fetch(`/api/exams/ai-schedule/${rescheduleTarget._id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ examDate: rsDate || undefined, startTime: rsTime || undefined }),
      });
      if (!res.ok) throw new Error((await res.json()).error);
      toast({ title: 'Exam rescheduled', description: `${rescheduleTarget.title} has been updated.` });
      setRescheduleTarget(null);
      loadData();
    } catch (e: any) {
      toast({ title: 'Error', description: e.message, variant: 'destructive' });
    } finally {
      setRescheduling(false);
    }
  };

  useEffect(() => { loadData(); }, []);

  const setSection = (key: keyof typeof sections, val: number) =>
    setSections(prev => ({ ...prev, [key]: Math.max(0, val) }));

  const toggleProgram = (p: string) =>
    setSelectedPrograms(prev => prev.includes(p) ? prev.filter(x => x !== p) : [...prev, p]);

  const toggleYear = (y: number) =>
    setSelectedYears(prev => prev.includes(y) ? prev.filter(x => x !== y) : [...prev, y]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!subject.trim()) {
      toast({ title: 'Missing subject', description: 'Enter the technical subject for this exam.', variant: 'destructive' });
      return;
    }
    if (totalQuestions < 5) {
      toast({ title: 'Too few questions', description: 'Total questions must be at least 5.', variant: 'destructive' });
      return;
    }
    if (!durationMins) {
      toast({ title: 'Missing duration', description: 'Please set the exam duration.', variant: 'destructive' });
      return;
    }

    const user = getCurrentUser();
    if (!user) return;
    const teacherId = (user as any)._id || (user as any).id;

    setGenerating(true);
    try {
      const aiRes = await fetch('/api/ai/generate-placement-exam', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          subject: subject.trim(),
          difficulty,
          sections: { technical: sections.technical, aptitude: sections.aptitude, reasoning: sections.reasoning, verbal: sections.verbal },
          companyType,
        }),
      });
      if (!aiRes.ok) throw new Error((await aiRes.json()).error || 'AI generation failed');
      const aiOutput = await aiRes.json();

      // Step 2: transform AI output to the exam question format
      const questions: ReviewQuestion[] = aiOutput.questions.map((q) => ({
        questionText: q.question,
        questionType: 'MCQ',
        options: q.options.map((text, i) => ({
          label: String.fromCharCode(65 + i),
          text,
          isCorrect: i === q.correctIndex,
        })),
        explanation: q.explanation,
        marks: 1,
        difficulty: difficulty === 'easy' ? 'Easy' : difficulty === 'hard' ? 'Hard' : 'Medium',
        topic: q.topic,
        section: q.section,
      }));

      // Step 3: hand off to the review screen — teacher can edit/remove before publishing
      setReviewQuestions(questions);
      setReviewTitle(customTitle.trim() || aiOutput.title);
    } catch (err: any) {
      toast({ title: 'Error generating exam', description: err.message, variant: 'destructive' });
    } finally {
      setGenerating(false);
    }
  };

  const updateReviewQuestion = (idx: number, patch: Partial<ReviewQuestion>) => {
    setReviewQuestions(prev => prev ? prev.map((q, i) => i === idx ? { ...q, ...patch } : q) : prev);
  };

  const updateReviewOption = (qIdx: number, oIdx: number, text: string) => {
    setReviewQuestions(prev => prev ? prev.map((q, i) => i === qIdx
      ? { ...q, options: q.options.map((o, j) => j === oIdx ? { ...o, text } : o) }
      : q) : prev);
  };

  const setCorrectOption = (qIdx: number, oIdx: number) => {
    setReviewQuestions(prev => prev ? prev.map((q, i) => i === qIdx
      ? { ...q, options: q.options.map((o, j) => ({ ...o, isCorrect: j === oIdx })) }
      : q) : prev);
  };

  const removeReviewQuestion = (idx: number) => {
    setReviewQuestions(prev => prev ? prev.filter((_, i) => i !== idx) : prev);
  };

  const discardReview = () => {
    setReviewQuestions(null);
    setReviewTitle('');
  };

  const handlePublish = async () => {
    if (!reviewQuestions || reviewQuestions.length === 0) {
      toast({ title: 'No questions', description: 'Add at least one question before publishing.', variant: 'destructive' });
      return;
    }

    const user = getCurrentUser();
    if (!user) return;
    const teacherId = (user as any)._id || (user as any).id;

    setPublishing(true);
    try {
      const res = await fetch('/api/exams/ai-schedule', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          teacherId,
          title:       reviewTitle,
          subject:     subject.trim(),
          description: `AI Placement Mock Test — ${subject.trim()} (${companyType})`,
          examDate,
          startTime,
          durationMins,
          shuffleQuestions: shuffleQ,
          shuffleOptions:   shuffleOpts,
          showResultImmediately: true,
          targetPrograms: selectedPrograms,
          targetYears:    selectedYears,
          questions: reviewQuestions,
        }),
      });

      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Failed to save exam');

      setLastCreated(data);
      setSuccessDialog(true);

      // Reset form + review
      setReviewQuestions(null);
      setReviewTitle('');
      setSubject('');
      setCustomTitle('');
      setSections({ technical: 15, aptitude: 10, reasoning: 10, verbal: 5 });
      setCompanyType('any');
      setDifficulty('medium');
      setExamDate('');
      setStartTime('');
      setDurationMins(60);
      setSelectedPrograms([]);
      setSelectedYears([]);

      // Refresh list
      const eRes = await fetch(`/api/exams/ai-schedule?teacherId=${teacherId}`);
      const eData = await eRes.json();
      setExams(Array.isArray(eData) ? eData : []);
    } catch (err: any) {
      toast({ title: 'Error publishing exam', description: err.message, variant: 'destructive' });
    } finally {
      setPublishing(false);
    }
  };

  // ── Review Screen ────────────────────────────────────────────────────────────
  if (reviewQuestions !== null) {
    const sectionCounts = SECTION_META.map(s => ({
      ...s,
      count: reviewQuestions.filter(q => q.section === s.key).length,
    }));

    return (
      <div className="space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between gap-4 flex-wrap">
          <div className="flex items-center gap-4">
            <div className="p-3 rounded-2xl bg-gradient-to-r from-violet-500 to-purple-600 text-white shadow-lg">
              <Sparkles className="h-7 w-7" />
            </div>
            <div>
              <h1 className="text-2xl font-bold text-slate-900">Review Generated Questions</h1>
              <p className="text-slate-500 text-sm">{reviewQuestions.length} questions generated — edit or remove before publishing.</p>
            </div>
          </div>
          <div className="flex gap-3">
            <Button variant="outline" onClick={discardReview} className="rounded-xl border-slate-200 text-slate-600">
              Discard & Start Over
            </Button>
            <Button
              onClick={handlePublish}
              disabled={publishing || reviewQuestions.length === 0}
              className="h-10 bg-gradient-to-r from-violet-600 to-purple-600 hover:from-violet-700 hover:to-purple-700 text-white rounded-xl font-semibold shadow-lg shadow-violet-500/20"
            >
              {publishing ? (
                <><Loader2 className="h-4 w-4 mr-2 animate-spin" /> Publishing…</>
              ) : (
                <><CheckCircle2 className="h-4 w-4 mr-2" /> Publish {reviewQuestions.length} Questions</>
              )}
            </Button>
          </div>
        </div>

        {/* Editable title */}
        <Card className="border-slate-200 shadow-sm">
          <CardContent className="pt-5 pb-5">
            <div className="space-y-2">
              <Label className="text-slate-700 font-medium">Exam Title</Label>
              <input
                className="w-full px-3 py-2 rounded-xl border border-slate-200 text-slate-800 font-semibold text-base focus:outline-none focus:ring-2 focus:ring-violet-300"
                value={reviewTitle}
                onChange={e => setReviewTitle(e.target.value)}
              />
            </div>
          </CardContent>
        </Card>

        {/* Section summary */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
          {sectionCounts.map(s => {
            const Icon = s.icon;
            return (
              <div key={s.key} className={`p-4 rounded-xl border ${s.border} ${s.bg} flex items-center gap-3`}>
                <Icon className={`h-5 w-5 ${s.color} flex-shrink-0`} />
                <div>
                  <p className={`text-lg font-black ${s.color}`}>{s.count}</p>
                  <p className="text-xs text-slate-500">{s.label}</p>
                </div>
              </div>
            );
          })}
        </div>

        {/* Questions list */}
        <div className="space-y-4">
          {reviewQuestions.map((q, qIdx) => {
            const sm = SECTION_META.find(s => s.key === q.section) ?? SECTION_META[0];
            const Icon = sm.icon;
            return (
              <Card key={qIdx} className={`border ${sm.border} shadow-sm`}>
                <CardContent className="pt-5 pb-5 space-y-4">
                  {/* Question header */}
                  <div className="flex items-start justify-between gap-3">
                    <div className="flex items-start gap-3 flex-1">
                      <span className={`mt-0.5 flex-shrink-0 w-7 h-7 rounded-full ${sm.bg} ${sm.color} text-xs font-bold flex items-center justify-center border ${sm.border}`}>
                        {qIdx + 1}
                      </span>
                      <div className="flex-1 space-y-2">
                        <div className={`flex items-center gap-2 text-xs font-semibold ${sm.color}`}>
                          <Icon className="h-3.5 w-3.5" />
                          <span className="uppercase tracking-wide">{sm.label}</span>
                          {q.topic && <span className="font-normal text-slate-400">· {q.topic}</span>}
                        </div>
                        <textarea
                          className="w-full text-sm font-medium text-slate-800 bg-transparent border-b border-dashed border-slate-200 focus:border-violet-400 focus:outline-none resize-none pb-1"
                          rows={2}
                          value={q.questionText}
                          onChange={e => updateReviewQuestion(qIdx, { questionText: e.target.value })}
                        />
                      </div>
                    </div>
                    <button
                      onClick={() => removeReviewQuestion(qIdx)}
                      className="p-1.5 rounded-lg text-slate-300 hover:text-red-500 hover:bg-red-50 transition-colors flex-shrink-0"
                      title="Remove question"
                    >
                      <Trash2 className="h-4 w-4" />
                    </button>
                  </div>

                  {/* Options */}
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 pl-10">
                    {q.options.map((opt, oIdx) => (
                      <div
                        key={oIdx}
                        className={`flex items-center gap-2 p-2 rounded-lg border cursor-pointer transition-all ${
                          opt.isCorrect
                            ? 'border-green-400 bg-green-50'
                            : 'border-slate-200 bg-white hover:border-violet-300'
                        }`}
                        onClick={() => setCorrectOption(qIdx, oIdx)}
                        title="Click to mark as correct"
                      >
                        <span className={`w-5 h-5 rounded-full flex-shrink-0 border-2 flex items-center justify-center text-xs font-bold ${
                          opt.isCorrect ? 'border-green-500 bg-green-500 text-white' : 'border-slate-300 text-slate-400'
                        }`}>
                          {opt.isCorrect ? '✓' : opt.label}
                        </span>
                        <input
                          className="flex-1 text-xs text-slate-700 bg-transparent border-none outline-none"
                          value={opt.text}
                          onChange={e => updateReviewOption(qIdx, oIdx, e.target.value)}
                          onClick={ev => ev.stopPropagation()}
                        />
                      </div>
                    ))}
                  </div>

                  {/* Explanation */}
                  {q.explanation && (
                    <div className="pl-10 p-3 rounded-lg bg-amber-50 border border-amber-200">
                      <p className="text-xs font-semibold text-amber-700 mb-1">Explanation</p>
                      <p className="text-xs text-slate-600">{q.explanation}</p>
                    </div>
                  )}
                </CardContent>
              </Card>
            );
          })}
        </div>

        {/* Sticky publish bar */}
        {reviewQuestions.length > 0 && (
          <div className="sticky bottom-4 flex justify-end gap-3 pt-2">
            <Button variant="outline" onClick={discardReview} className="rounded-xl border-slate-300">
              Discard
            </Button>
            <Button
              onClick={handlePublish}
              disabled={publishing}
              className="bg-gradient-to-r from-violet-600 to-purple-600 hover:from-violet-700 hover:to-purple-700 text-white rounded-xl font-semibold shadow-xl shadow-violet-500/30"
            >
              {publishing ? (
                <><Loader2 className="h-4 w-4 mr-2 animate-spin" /> Publishing…</>
              ) : (
                <><CheckCircle2 className="h-4 w-4 mr-2" /> Publish {reviewQuestions.length} Questions</>
              )}
            </Button>
          </div>
        )}

        {/* Success dialog */}
        <Dialog open={successDialog} onOpenChange={setSuccessDialog}>
          <DialogContent className="sm:max-w-md">
            <DialogHeader>
              <DialogTitle className="flex items-center gap-2 text-green-700">
                <CheckCircle2 className="h-6 w-6" /> Placement Test Scheduled!
              </DialogTitle>
              <DialogDescription>
                The AI has generated and published your placement mock test. Students can take it from the Exam Arena.
              </DialogDescription>
            </DialogHeader>
            {lastCreated && (
              <div className="space-y-2 py-2 text-sm text-slate-700">
                <div className="flex justify-between"><span className="text-slate-500">Title</span><span className="font-medium text-right max-w-[220px] truncate">{lastCreated.title}</span></div>
                <div className="flex justify-between"><span className="text-slate-500">Subject</span><span>{lastCreated.subject}</span></div>
                <div className="flex justify-between"><span className="text-slate-500">Questions</span><span>{lastCreated.totalQuestions}</span></div>
                <div className="flex justify-between"><span className="text-slate-500">Duration</span><span>{lastCreated.durationMins} minutes</span></div>
                <div className="flex justify-between"><span className="text-slate-500">Status</span><span className="text-green-600 font-semibold">Published</span></div>
              </div>
            )}
            <DialogFooter>
              <Button onClick={() => setSuccessDialog(false)} className="w-full bg-gradient-to-r from-violet-600 to-purple-600 text-white rounded-xl">
                Done
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </div>
    );
  }

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="flex items-center gap-4">
        <div className="p-3 rounded-2xl bg-gradient-to-r from-violet-500 to-purple-600 text-white shadow-lg">
          <Sparkles className="h-7 w-7" />
        </div>
        <div>
          <h1 className="text-2xl font-bold text-slate-900">Schedule Placement Test</h1>
          <p className="text-slate-500 text-sm">AI generates a full placement-style mock test — technical, aptitude, reasoning, and verbal</p>
        </div>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-3 gap-8">
        {/* ── Form ── */}
        <div className="xl:col-span-2 space-y-5">
          <form onSubmit={handleSubmit} className="space-y-5">

            {/* Subject + Company type */}
            <Card className="border-slate-200 shadow-sm">
              <CardHeader className="pb-3">
                <CardTitle className="text-base text-slate-800">Exam Details</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label className="text-slate-700 font-medium">
                      Technical Subject / Domain <span className="text-red-500">*</span>
                    </Label>
                    <Input
                      value={subject}
                      onChange={e => setSubject(e.target.value)}
                      placeholder="e.g. Data Structures, Java, DBMS, Python"
                      className="rounded-xl border-slate-200"
                    />
                    <p className="text-xs text-slate-400">AI uses industry-standard knowledge for this subject — not limited to syllabus.</p>
                  </div>
                  <div className="space-y-2">
                    <Label className="text-slate-700 font-medium">Difficulty</Label>
                    <Select value={difficulty} onValueChange={setDifficulty}>
                      <SelectTrigger className="rounded-xl border-slate-200">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        {DIFFICULTIES.map(d => (
                          <SelectItem key={d.value} value={d.value}>{d.label}</SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                </div>

                {/* Company type */}
                <div className="space-y-2">
                  <Label className="text-slate-700 font-medium">Target Company Type</Label>
                  <div className="grid grid-cols-2 gap-2">
                    {COMPANY_TYPES.map(ct => (
                      <button
                        type="button"
                        key={ct.value}
                        onClick={() => setCompanyType(ct.value)}
                        className={`p-3 rounded-xl border text-left transition-all ${
                          companyType === ct.value
                            ? 'border-violet-500 bg-violet-50 ring-2 ring-violet-300'
                            : 'border-slate-200 hover:border-violet-300 bg-white'
                        }`}
                      >
                        <p className="text-sm font-semibold text-slate-800">{ct.label}</p>
                        <p className="text-xs text-slate-500 mt-0.5">{ct.desc}</p>
                      </button>
                    ))}
                  </div>
                </div>

                <div className="space-y-2">
                  <Label className="text-slate-700 font-medium">
                    Custom Title <span className="text-slate-400 font-normal text-xs">(optional)</span>
                  </Label>
                  <Input
                    value={customTitle}
                    onChange={e => setCustomTitle(e.target.value)}
                    placeholder="AI will generate one if left blank"
                    className="rounded-xl border-slate-200"
                  />
                </div>
              </CardContent>
            </Card>

            {/* Section distribution */}
            <Card className="border-slate-200 shadow-sm">
              <CardHeader className="pb-3">
                <CardTitle className="text-base text-slate-800">Section Distribution</CardTitle>
                <CardDescription>Set how many questions to generate per section. Total: <strong>{totalQuestions} questions</strong></CardDescription>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-2 gap-3">
                  {SECTION_META.map(s => {
                    const Icon = s.icon;
                    const val  = sections[s.key];
                    return (
                      <div key={s.key} className={`p-4 rounded-xl border ${s.border} ${s.bg} space-y-2`}>
                        <div className={`flex items-center gap-2 ${s.color}`}>
                          <Icon className="h-4 w-4" />
                          <span className="text-sm font-semibold">{s.label}</span>
                        </div>
                        <div className="flex items-center gap-2">
                          <button
                            type="button"
                            onClick={() => setSection(s.key, val - 1)}
                            className="w-7 h-7 rounded-lg bg-white border border-slate-200 text-slate-600 font-bold hover:bg-slate-50 transition-colors"
                          >−</button>
                          <input
                            type="number"
                            min={0}
                            max={50}
                            value={val}
                            onChange={e => setSection(s.key, Number(e.target.value))}
                            className={`w-14 text-center text-lg font-bold ${s.color} bg-transparent border-none outline-none`}
                          />
                          <button
                            type="button"
                            onClick={() => setSection(s.key, val + 1)}
                            className="w-7 h-7 rounded-lg bg-white border border-slate-200 text-slate-600 font-bold hover:bg-slate-50 transition-colors"
                          >+</button>
                        </div>
                        <p className="text-xs text-slate-400">{val} question{val !== 1 ? 's' : ''}</p>
                      </div>
                    );
                  })}
                </div>
                {totalQuestions < 5 && (
                  <p className="mt-3 text-xs text-red-500">Total must be at least 5 questions.</p>
                )}
              </CardContent>
            </Card>

            {/* Schedule */}
            <Card className="border-slate-200 shadow-sm">
              <CardHeader className="pb-3">
                <CardTitle className="text-base text-slate-800">Schedule</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                  <div className="space-y-2">
                    <Label className="text-slate-700 font-medium flex items-center gap-1.5">
                      <Calendar className="h-4 w-4 text-violet-500" /> Exam Date
                    </Label>
                    <Input type="date" value={examDate} onChange={e => setExamDate(e.target.value)} className="rounded-xl border-slate-200" />
                  </div>
                  <div className="space-y-2">
                    <Label className="text-slate-700 font-medium flex items-center gap-1.5">
                      <Clock className="h-4 w-4 text-violet-500" /> Start Time
                    </Label>
                    <Input type="time" value={startTime} onChange={e => setStartTime(e.target.value)} className="rounded-xl border-slate-200" />
                  </div>
                  <div className="space-y-2">
                    <Label className="text-slate-700 font-medium">Duration (mins) <span className="text-red-500">*</span></Label>
                    <Input
                      type="number" min={10} max={300}
                      value={durationMins}
                      onChange={e => setDurationMins(Number(e.target.value))}
                      className="rounded-xl border-slate-200"
                    />
                  </div>
                </div>

                {/* Target audience */}
                <div className="space-y-3">
                  <Label className="text-slate-700 font-medium flex items-center gap-1.5">
                    <Users className="h-4 w-4 text-violet-500" /> Target Audience
                  </Label>
                  <div className="p-4 rounded-xl border border-slate-200 bg-slate-50 space-y-3">
                    <div>
                      <p className="text-xs font-medium text-slate-500 mb-2">Programs</p>
                      <div className="flex flex-wrap gap-2">
                        {PROGRAMS.map(p => (
                          <button
                            type="button" key={p}
                            onClick={() => toggleProgram(p)}
                            className={`px-3 py-1 rounded-full text-sm font-medium border transition-all ${
                              selectedPrograms.includes(p)
                                ? 'bg-violet-600 text-white border-violet-600'
                                : 'bg-white text-slate-600 border-slate-200 hover:border-violet-400'
                            }`}
                          >{p}</button>
                        ))}
                      </div>
                    </div>
                    <div>
                      <p className="text-xs font-medium text-slate-500 mb-2">Years</p>
                      <div className="flex gap-2">
                        {YEARS.map(y => (
                          <button
                            type="button" key={y}
                            onClick={() => toggleYear(y)}
                            className={`w-10 h-10 rounded-xl text-sm font-bold border transition-all ${
                              selectedYears.includes(y)
                                ? 'bg-violet-600 text-white border-violet-600'
                                : 'bg-white text-slate-600 border-slate-200 hover:border-violet-400'
                            }`}
                          >{y}</button>
                        ))}
                      </div>
                    </div>
                  </div>
                </div>

                {/* Shuffle options */}
                <div className="flex flex-wrap gap-4">
                  <label className="flex items-center gap-2 cursor-pointer select-none">
                    <input type="checkbox" checked={shuffleQ} onChange={e => setShuffleQ(e.target.checked)} className="rounded accent-violet-600" />
                    <span className="text-sm text-slate-600">Shuffle Questions</span>
                  </label>
                  <label className="flex items-center gap-2 cursor-pointer select-none">
                    <input type="checkbox" checked={shuffleOpts} onChange={e => setShuffleOpts(e.target.checked)} className="rounded accent-violet-600" />
                    <span className="text-sm text-slate-600">Shuffle Options</span>
                  </label>
                </div>
              </CardContent>
            </Card>

            <Button
              type="submit"
              disabled={generating || !subject.trim() || totalQuestions < 5}
              className="w-full h-12 bg-gradient-to-r from-violet-600 to-purple-600 hover:from-violet-700 hover:to-purple-700 text-white rounded-xl font-semibold shadow-lg shadow-violet-500/25 transition-all"
            >
              {generating ? (
                <><Loader2 className="h-5 w-5 mr-2 animate-spin" /> AI is generating {totalQuestions} questions…</>
              ) : (
                <><Sparkles className="h-5 w-5 mr-2" /> Generate & Schedule Placement Test</>
              )}
            </Button>
            {generating && (
              <p className="text-center text-sm text-slate-500 animate-pulse">
                Generating {totalQuestions} questions across {Object.values(sections).filter(v => v > 0).length} sections — this may take 20–40 seconds…
              </p>
            )}
          </form>
        </div>

        {/* ── Right sidebar ── */}
        <div className="space-y-4">
          <Card className="border-slate-200 shadow-sm">
            <CardHeader className="pb-3">
              <CardTitle className="text-base text-slate-800 flex items-center gap-2">
                <ClipboardList className="h-5 w-5 text-violet-500" /> How it works
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-3 text-sm text-slate-600">
              {[
                'Enter the technical subject (e.g. "Java", "DBMS").',
                'Set section distribution — Technical, Aptitude, Reasoning, Verbal.',
                'Choose company type to match question style.',
                'AI generates questions from industry knowledge — not limited to any syllabus.',
                'Optionally attach a course syllabus as extra context.',
                'Exam is published instantly for students in the Exam Arena.',
              ].map((step, i) => (
                <div key={i} className="flex gap-3">
                  <span className="mt-0.5 flex-shrink-0 w-5 h-5 rounded-full bg-violet-100 text-violet-600 text-xs font-bold flex items-center justify-center">{i + 1}</span>
                  <span>{step}</span>
                </div>
              ))}
            </CardContent>
          </Card>

          <Card className="border-slate-200 shadow-sm">
            <CardHeader className="pb-3">
              <CardTitle className="text-base text-slate-800">Sections</CardTitle>
            </CardHeader>
            <CardContent className="space-y-2 text-sm">
              {SECTION_META.map(s => (
                <div key={s.key} className="flex justify-between items-center">
                  <span className={`font-medium ${s.color}`}>{s.label}</span>
                  <span className="font-bold text-slate-700">{sections[s.key]} Qs</span>
                </div>
              ))}
              <div className="border-t border-slate-100 pt-2 flex justify-between font-bold text-slate-900">
                <span>Total</span>
                <span>{totalQuestions} Qs</span>
              </div>
            </CardContent>
          </Card>

          <Card className="border-slate-200 shadow-sm">
            <CardHeader className="pb-3">
              <CardTitle className="text-base text-slate-800">Stats</CardTitle>
            </CardHeader>
            <CardContent className="space-y-2 text-sm">
              <div className="flex justify-between">
                <span className="text-slate-500">Total Exams Scheduled</span>
                <span className="font-bold text-slate-800">{exams.length}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-500">Published</span>
                <span className="font-bold text-green-600">{exams.filter(e => e.status === 'published').length}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-500">Completed</span>
                <span className="font-bold text-blue-600">{exams.filter(e => e.status === 'completed').length}</span>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>

      {/* ── Exams table ── */}
      <Card className="border-slate-200 shadow-sm">
        <CardHeader className="pb-4">
          <CardTitle className="text-lg text-slate-800 flex items-center gap-2">
            <ClipboardList className="h-5 w-5 text-violet-500" /> Scheduled Placement Tests
          </CardTitle>
        </CardHeader>
        <CardContent>
          {loadingData ? (
            <div className="flex justify-center py-10">
              <Loader2 className="h-6 w-6 animate-spin text-violet-500" />
            </div>
          ) : exams.length === 0 ? (
            <div className="text-center py-12 text-slate-400">
              <Sparkles className="h-10 w-10 mx-auto mb-3 opacity-30" />
              <p className="font-medium">No placement tests scheduled yet</p>
              <p className="text-sm mt-1">Use the form above to generate your first AI placement test.</p>
            </div>
          ) : (
            <div className="overflow-x-auto rounded-xl border border-slate-100">
              <table className="w-full text-sm">
                <thead>
                  <tr className="bg-slate-50 border-b border-slate-100">
                    <th className="text-left px-4 py-3 text-slate-500 font-medium">Title</th>
                    <th className="text-left px-4 py-3 text-slate-500 font-medium">Subject</th>
                    <th className="text-left px-4 py-3 text-slate-500 font-medium">Date</th>
                    <th className="text-left px-4 py-3 text-slate-500 font-medium">Time</th>
                    <th className="text-center px-4 py-3 text-slate-500 font-medium">Duration</th>
                    <th className="text-center px-4 py-3 text-slate-500 font-medium">Questions</th>
                    <th className="text-center px-4 py-3 text-slate-500 font-medium">Status</th>
                    <th className="text-left px-4 py-3 text-slate-500 font-medium">Created</th>
                    <th className="text-center px-4 py-3 text-slate-500 font-medium">Reschedule</th>
                    <th className="text-center px-4 py-3 text-slate-500 font-medium">Results</th>
                  </tr>
                </thead>
                <tbody>
                  {exams.map((exam, idx) => (
                    <tr key={exam._id} className={`border-b border-slate-50 hover:bg-slate-50 transition-colors ${idx % 2 === 0 ? '' : 'bg-slate-50/30'}`}>
                      <td className="px-4 py-3 font-medium text-slate-800 max-w-[200px] truncate">{exam.title}</td>
                      <td className="px-4 py-3 text-slate-600">{exam.subject || '—'}</td>
                      <td className="px-4 py-3 text-slate-600">{exam.examDate ? formatDate(exam.examDate) : '—'}</td>
                      <td className="px-4 py-3 text-slate-600">{exam.startTime || '—'}</td>
                      <td className="px-4 py-3 text-center text-slate-600">{exam.durationMins} min</td>
                      <td className="px-4 py-3 text-center font-medium text-slate-700">{exam.totalQuestions}</td>
                      <td className="px-4 py-3 text-center">
                        <span className={`px-2 py-0.5 rounded-full text-xs font-semibold capitalize ${statusColor(exam.status)}`}>{exam.status}</span>
                      </td>
                      <td className="px-4 py-3 text-slate-400 text-xs">{formatDate(exam.createdAt)}</td>
                      <td className="px-4 py-3 text-center">
                        <button
                          onClick={() => { setRsDate(exam.examDate || ''); setRsTime(exam.startTime || ''); setRescheduleTarget(exam); }}
                          className="inline-flex items-center gap-1 text-xs text-violet-600 hover:text-violet-800 font-medium hover:underline"
                        >
                          <Calendar className="h-3.5 w-3.5" /> Edit
                        </button>
                      </td>
                      <td className="px-4 py-3 text-center">
                        <button
                          onClick={() => router.push(`/dashboard/teacher/schedule-exam/results/${exam._id}`)}
                          className="inline-flex items-center gap-1 text-xs text-indigo-600 hover:text-indigo-800 font-medium hover:underline"
                        >
                          <BarChart2 className="h-3.5 w-3.5" /> View
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Reschedule dialog */}
      <Dialog open={!!rescheduleTarget} onOpenChange={open => { if (!open) setRescheduleTarget(null); }}>
        <DialogContent className="sm:max-w-sm">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2 text-slate-900">
              <Calendar className="h-5 w-5 text-violet-500" /> Reschedule Exam
            </DialogTitle>
            <DialogDescription>
              Update the date and/or time for <strong>{rescheduleTarget?.title}</strong>.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-2">
            <div className="space-y-1.5">
              <Label htmlFor="rs-date">New Date</Label>
              <Input id="rs-date" type="date" value={rsDate} onChange={e => setRsDate(e.target.value)} />
            </div>
            <div className="space-y-1.5">
              <Label htmlFor="rs-time">New Start Time</Label>
              <Input id="rs-time" type="time" value={rsTime} onChange={e => setRsTime(e.target.value)} />
            </div>
          </div>
          <DialogFooter className="gap-2">
            <Button variant="outline" onClick={() => setRescheduleTarget(null)} className="rounded-xl">Cancel</Button>
            <Button
              onClick={handleReschedule}
              disabled={rescheduling || (!rsDate && !rsTime)}
              className="rounded-xl bg-violet-600 hover:bg-violet-700 text-white"
            >
              {rescheduling ? <><Loader2 className="h-4 w-4 mr-2 animate-spin" />Saving…</> : 'Save Schedule'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Success dialog */}
      <Dialog open={successDialog} onOpenChange={setSuccessDialog}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2 text-green-700">
              <CheckCircle2 className="h-6 w-6" /> Placement Test Scheduled!
            </DialogTitle>
            <DialogDescription>
              The AI has generated and published your placement mock test. Students can take it from the Exam Arena.
            </DialogDescription>
          </DialogHeader>
          {lastCreated && (
            <div className="space-y-2 py-2 text-sm text-slate-700">
              <div className="flex justify-between"><span className="text-slate-500">Title</span><span className="font-medium text-right max-w-[220px] truncate">{lastCreated.title}</span></div>
              <div className="flex justify-between"><span className="text-slate-500">Subject</span><span>{lastCreated.subject}</span></div>
              <div className="flex justify-between"><span className="text-slate-500">Questions</span><span>{lastCreated.totalQuestions}</span></div>
              <div className="flex justify-between"><span className="text-slate-500">Duration</span><span>{lastCreated.durationMins} minutes</span></div>
              <div className="flex justify-between"><span className="text-slate-500">Status</span><span className="text-green-600 font-semibold">Published</span></div>
            </div>
          )}
          <DialogFooter>
            <Button onClick={() => setSuccessDialog(false)} className="w-full bg-gradient-to-r from-violet-600 to-purple-600 text-white rounded-xl">
              Done
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
